### ISSUE TITLE
Bug: Scrollbar not showing on new page

### ISSUE THREAD

**Issue by nathanielheitsch** [hyperfluid-tech/rotary_scrollbar#7]
WearOS guidelines require scroll views to show the scrollbar on opening of the screen.

This does not work with this plugin until the view is scrolled.

**Comment by gilnobrega** [comment]
Thanks for raising this issue!

Fixed by PR #9 

https://github.com/hyperfluid-tech/rotary_scrollbar/assets/82336674/586ff095-1200-46d9-9a86-ac151dd18174
